name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t ./lib

      - name: Get version from plugin.json
        id: version
        run: |
          echo "version=$(python -c "import json; print(json.load(open('plugin.json'))['Version'])" )" >> $GITHUB_OUTPUT

      - name: Package plugin
        run: |
          zip -r "hz-plugin.zip" . -x "*.git*" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "hz-plugin.zip"
          generate_release_notes: true
